services:
  mongodb:
    image: mongo:latest
    container_name: dock-demo-mongodb-1
    environment:
      - 'MONGO_INITDB_DATABASE: mydatabase'
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
